#!/usr/bin/env python
"""This script performs a local AES-256-GCM encrypt and decrypt operation"""

import pprint
from Crypto.Cipher import AES


def encrypt(key, message):
    """encrypt"""
    encryption_cipher = AES.new(key, AES.MODE_GCM)
    nonce = encryption_cipher.nonce
    ciphertext, tag = encryption_cipher.encrypt_and_digest(message)
    return (nonce, tag, ciphertext)


def decrypt(key, nonce, tag, ciphertext):
    """decrypt"""
    decryption_cipher = AES.new(key, AES.MODE_GCM, nonce)
    return decryption_cipher.decrypt_and_verify(ciphertext, tag)


def main():
    """Main"""
    message = "Attack at dawn"
    key = "ThisIsASecretKeyAReallySecretKey"

    nonce, tag, ciphertext = encrypt(key, message)
    plaintext = decrypt(key, nonce, tag, ciphertext)
    pprint.pprint(plaintext)


if __name__ == '__main__':
    main()
