#!/usr/bin/env python
"""This script performs a symmetric encrypt and decrypt operation using a KMS master key"""

from pprint import pprint
import boto3
import base64


def main():
    """Main"""
    kms = boto3.client('kms')
    key_id = kms.describe_key(KeyId='alias/workshop')["KeyMetadata"]["KeyId"]

    cipher_text = kms.encrypt(
        KeyId=key_id,
        Plaintext="Attack at dawn"
    )

    pprint(base64.b64encode(cipher_text['CiphertextBlob']))

    plain_text = kms.decrypt(
        CiphertextBlob=cipher_text['CiphertextBlob']
    )

    pprint(plain_text['Plaintext'])


if __name__ == '__main__':
    main()
