#!/usr/bin/env python
"""This script wraps Scout2 and prints dangerous findings"""


from os import system
from subprocess import call
from json import load

call(["Scout2", "--no-browser"])
system("tail -n +2 scout2-report/inc-awsconfig/aws_config.js > scout2-report/inc-awsconfig/data.js")

with open("scout2-report/inc-awsconfig/data.js") as data_file:
    data = load(data_file)

danger_issues = False

for service, results in data["services"].iteritems():
    if "findings" in results and results["findings"] is not None:
        for rule, details in results["findings"].iteritems():
            if details["flagged_items"] > 0 and details["level"] == "danger":
                danger_issues = True
                print "[%s] %s : %s" % (service, details["description"], details["flagged_items"])

if danger_issues:
    print "Scout2 danger issues identified. Please correct the issues listed above. See scout2-report/report.html for more details"
    exit(1)
else:
    print "Congratulations, Scout 2 did not find any dangerous issues"
